### ISSUE TITLE
Unable to download pretrained models.

### ISSUE THREAD

**Issue by PAAYAS** [tentacool9/accent_conversion_deep_learning#1]
Dear Author,
I am unable to open the drive link to access the pretrained models as it says, "The requested URL was not found on this server". Hope you update the link once again.

**Comment by davidschiff100** [comment]
Hi, it was deleted by mistake. Will be fixed in a matter of a week

**Comment by davidschiff100** [comment]
Hi sorry about the delay, I fixed the link
